##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. Use of this
## source code is governed by an MIT-style license that can be found in the
## LICENSE file located in this project's root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_pod
description: A package offering tools to manage app state using ValueNotifier-like objects called Pods.
version: 0.11.15
repository: https://github.com/robmllze/df_pod
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - bloc
  - dependency-injection
  - reactive
  - riverpod
  - state-management

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_type: ^0.5.13
  df_cleanup: ^0.2.2

  shared_preferences: ^2.3.2
  tuple: ^2.0.2
  equatable: ^2.0.5
  meta: ^1.15.0

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  df_log: ^0.2.1
  get_it: ^7.7.0
