##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. Use of this
## source code is governed by an MIT-style license that can be found in the
## LICENSE file.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_pod
description: A package offering tools to manage app state using ValueNotifier-like objects called Pods.
version: 0.6.0
repository: https://github.com/robmllze/df_pod
# homepage: TODO
# documentation: TODO
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - bloc
  - dependency-injection
  - reactive-programming
  - state
  - state-management

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.1
  tuple: ^2.0.2
  df_type: ^0.2.2
  equatable: ^2.0.5
  # analyzer: ^6.8.0
  # meta: ^1.15.0

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  df_log: ^0.2.1
  get_it: ^7.7.0
